### ISSUE TITLE
Matching array of objects

### ISSUE THREAD

**Issue by tulios** [jondot/hypermatch#2]
Hi, I have an array of objects and I was wondering if you would accept new operators to allow this type of matching. I've implemented `any`, `all`, `one`, and `none` operators to further improve the use of collections, they look like this:

```javascript
const data = {
  users: [
    { 'user': 'john', 'age': 36, 'active': true },
    { 'user': 'johnathan', 'age': 40, 'active': false },
    { 'user': 'johny', 'age': 21, 'active': true }
  ]
}

const rules = [
    'all',
    'users',
     ['and',
       ['regex', 'user', '^john'],
       ['exists', 'active']]]

run(rules, data) // => false
```

They all work in a similar way, any thoughts?

**Comment by jondot** [comment]
merged.
