### ISSUE TITLE
Requires babel-runtime even when running in Nodejs

### ISSUE THREAD

**Issue by Nevon** [jondot/hypermatch#4]
I'm using Hypermatch in node, and because the entrypoint points to a compiled file that requires babel-runtime, it fails to run in production (as we don't install dev dependencies there).

We worked around the problem for now by requiring directly from `hypermatch/src`, so that we get the source version, but it's a bit nasty.

**Comment by jondot** [comment]
Should be fixed now. Note the new version is `1.1.0`.
